### ISSUE TITLE
some webs shown multiple times in a graph

### ISSUE THREAD

**Issue by rplevka** [rplevka/conspi#23]
i spot this one:
'svetkolemnas .info'
The first one is an initil seed and there's one more as discovered node (it has no connections at all, should be easy to find).

Only the initial one should be created with its sore incremented

**Comment by rplevka** [comment]
ok, this happens for the very first web in the `nodes` array.
This is because the index of such item is `0` which in javascript is equal to `false` :))

``` js
> 0 == false
> true
```

Due to design of `getByValue()` function, this returns `false` in case the item is not in the array,
which is the same as if it is actually found and the return value is `0`

The fix is to use `-1` in case the element is not found.

**Comment by adammertel** [comment]
:+1:
